Repository onetime-with-members/backend, pull requests merged in 2025-08, with the labels that each got.

#264 [fix] : 필터링 참여자 대상 최적 시간 조회 시, 모두 되는 시간이 없어 빈 리스트를 반환하여 발생하는 문제를 해결한다
  src/main/java/side/onetime/service/EventService.java
  src/main/resources/application-local.yaml
Labels: 🚨 fix, 🚀 feat, 🔄 refactor, 😉 seongmin

#265 [release] : v1.5.1
  src/main/java/side/onetime/service/EventService.java
  src/main/resources/application-local.yaml
Labels: 💫 release

#267 [feat] : 개인 요일/날짜 스케줄 조회 시 N+1 문제를 해결한다
  src/main/java/side/onetime/repository/SelectionRepository.java
  src/main/java/side/onetime/service/ScheduleService.java
Labels: 🌱 style, 🚀 feat, 🔄 refactor, 😉 seongmin

#269 [feat] : 배너, 띠배너 엔티티 분리 및 배너 CRUD API를 구현한다
  .github/workflows/dev-cicd.yaml
  build.gradle
  deploy/deploy.sh
  src/main/java/side/onetime/controller/AdminController.java
  src/main/java/side/onetime/controller/BannerController.java
  src/main/java/side/onetime/domain/Banner.java
  src/main/java/side/onetime/domain/BarBanner.java
  src/main/java/side/onetime/dto/admin/request/RegisterBannerRequest.java
  src/main/java/side/onetime/dto/admin/request/RegisterBarBannerRequest.java
  src/main/java/side/onetime/dto/admin/request/UpdateBannerRequest.java
  src/main/java/side/onetime/dto/admin/request/UpdateBarBannerRequest.java
  src/main/java/side/onetime/dto/admin/response/GetActivatedBannerResponse.java
  src/main/java/side/onetime/dto/admin/response/GetAllActivatedBannersResponse.java
  src/main/java/side/onetime/dto/admin/response/GetAllActivatedBarBannersResponse.java
  src/main/java/side/onetime/dto/admin/response/GetAllBarBannersResponse.java
  src/main/java/side/onetime/dto/admin/response/GetBannerResponse.java
  src/main/java/side/onetime/dto/admin/response/GetBarBannerResponse.java
  src/main/java/side/onetime/exception/status/AdminErrorStatus.java
  src/main/java/side/onetime/global/common/status/SuccessStatus.java
  src/main/java/side/onetime/global/config/SecurityConfig.java
  src/main/java/side/onetime/global/filter/JwtFilter.java
  src/main/java/side/onetime/global/filter/RequestWrapperFilter.java
  src/main/java/side/onetime/repository/BannerRepository.java
  src/main/java/side/onetime/repository/BarBannerRepository.java
  src/main/java/side/onetime/service/AdminService.java
  src/main/java/side/onetime/util/S3Util.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/test/java/side/onetime/admin/AdminControllerTest.java
  src/test/java/side/onetime/admin/BannerControllerTest.java
Labels: 🚨 fix, 🚀 feat, 🔄 refactor, 😉 seongmin
